spring:
  application:
    name: devtiro-spring-boot-course
  datasource:
    url: jdbc:h2:mem:some_strange_name_for_a_database
    driver-class-name: org.h2.Driver
    username: sa
    password: assw0rd